# Generated by Django 4.1.3 on 2022-11-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('DateCreate', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=450)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
