# Generated by Django 4.1.3 on 2022-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Creater',
            field=models.CharField(default=121, max_length=45),
            preserve_default=False,
        ),
    ]
