# Generated by Django 4.1.3 on 2022-11-24 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0003_game_creater'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.game')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valuta', models.CharField(max_length=45)),
                ('Money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ID_Wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
